project: 
  type: website
  
website: 
  title: "The Mathematical System of Geometry"
  navbar: 
    left: 
      - IMsGEOMETRY8.qmd
      
TOPIC: THE MATHEMATICAL SYSTEM OF GEOMETRY

LESSON 2: DEFINED TERMS, UNDEFINED TERMS, POSTULATES AND THEOREMS
      
Lesson Objectives:

At the end of the lesson, the students should be able to:

illustrates defined terms, undefined terms, postulates and theorems; and

identify the postulates or theorems being referred in the given statement.

What's in!

Recall: Point, Line, and Plane

Directions: Determine whether each of the following suggests a point, a line or a plane.

straight wire

pinhole

sheet of paper

period

stick

Whatâ€™s New Directions: Write something about the following terms using your previous learning in geometry.

Point

Line

Plane

What is It

Points, lines, and planes are the building blocks of geometry. They are the undefined terms in geometry because they can be described without using other figures.

undefined term

illustration

how to name

other information

point

Dot





read as: point P

â€¢ Has no length, width, or space; occupies space. no â€¢ Examples: dot, dust particle, period

line

Straight mark with two arrow heads



 or Line AB or line â„“

â€¢ Has infinite length but no width thickness. â€¢ Examples: straight stick and wire,

plane

Slanted four-sided figure



Plane M or plane ABC

â€¢ Extends infinitely in two dimensions. No thickness. â€¢ Examples: Sheet of paper, wall

The undefined terms are used to define other geometric concepts. Here are some of the defined terms formed from the undefined terms.

Postulates and Theorems

Postulates also known as axioms are statements accepted as true without proof.

POSTULATE

ILLUSTRATIONS

1.A line and a plane contain an infinite number of points.

2. Line Postulate Two points determine exactly one line.



3. Plane Postulate Three noncolinear points determine a plane.



4. If two points are on a plane, then the line containing them is at the same plane.



5. If two planes intersect, then their intersection is a line.



Theorems are statements that need to be proven using any postulate or theorem.

Whatâ€™s More

Now itâ€™s your turn!

Answer the activity below to solidify your understanding and skills of the topic.

Activity 1.2

I. Directions: Illustrate and label the following.

Line CD

Point C on plane D

Three non-colinear points A, B and C on plane K.

Lines l and m intersect at point X.

Planes P and R intersect at line AB.

<!-- -->

Directions: State the postulate or theorem that makes each of statement true. Refer to the postulates and theorems stated above.

Given: three non-colinear points P, Q and R.

Points P and Q lie in line segment ğ‘ƒğ‘„.

Points P, Q and R are contained in plane PQR.

line segment ğ‘ƒğ‘„ lies on plane PQR.

line segment ğ‘ƒğ‘„ and point R lie on plane PQR.

line segment ğ‘ƒğ‘„ and line segmentğ‘„ğ‘…intersect only at point Q.

What's Need To Remember  


Points, lines and planes are the building blocks of geometry.

â€¢ Points
1. A point has no length, width and space. 
2. A line has infinite length but no width and thickness.  
3. A plane extends infinitely in two dimensions. No thickness. 
â€¢ Postulates  
1. A line and a plane contain an infinite number of points. 
2. Line Postulate. Two points determine exactly one line. 
3. Plane Postulate. Three noncollinear points determine a 
plane. 
4. If two points are on a plane, then the line containing them 
is at the same plane. 
5. If two planes intersect, then their intersection is a line. 
â€¢ Theorems 
1. Two lines intersect at one point. 
2. A line and a point not on the line determine a plane. 
3. Two intersecting lines determine a plane. 
4. The intersection of a line and a plane is a point. 

Assignment 

Think of a real-life situation that can represent the postulate or theorem 
illustrated above. Write at least 3.  
Example: the ground and the tripod of the camera. This illustrates the 
postulate number 3 - three noncollinear points determine a plane.

